/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor_project_ii;

import javax.swing.JOptionPane;

/**
 *
 * @author vaibh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public Login() {
        initComponents();
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("login.png")));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdLogin = new javax.swing.JTabbedPane();
        pnlAdmin = new javax.swing.JPanel();
        lblUserNameAdmin = new javax.swing.JLabel();
        lblPasswordAdmin = new javax.swing.JLabel();
        txtUserNameAdmin = new javax.swing.JTextField();
        txtPasswordAdmin = new javax.swing.JPasswordField();
        btnLoginAdmin = new javax.swing.JButton();
        btnResetAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlStaff = new javax.swing.JPanel();
        lblUserNameStaff = new javax.swing.JLabel();
        lblPasswordStaff = new javax.swing.JLabel();
        txtUserNameStaff = new javax.swing.JTextField();
        txtPasswordStaff = new javax.swing.JPasswordField();
        btnLoginStaff = new javax.swing.JButton();
        btnResetStaff = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlStudent = new javax.swing.JPanel();
        lblUserNameStudent = new javax.swing.JLabel();
        lblPasswordStudent = new javax.swing.JLabel();
        txtUserNameStudent = new javax.swing.JTextField();
        txtPasswordStudent = new javax.swing.JPasswordField();
        btnLoginStudent = new javax.swing.JButton();
        btnResetStudent = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);

        tbdLogin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        pnlAdmin.setAutoscrolls(true);

        lblUserNameAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblUserNameAdmin.setText("User_ID:");

        lblPasswordAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblPasswordAdmin.setText("Password:");

        txtUserNameAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        txtPasswordAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        btnLoginAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnLoginAdmin.setText("Login");
        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdminActionPerformed(evt);
            }
        });

        btnResetAdmin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnResetAdmin.setText("Reset");
        btnResetAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAdminActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor_project_ii/login_background.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblPasswordAdmin)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnLoginAdmin))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(txtUserNameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblUserNameAdmin))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnResetAdmin))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPasswordAdmin))
                    .addComponent(txtPasswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnLoginAdmin))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txtUserNameAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblUserNameAdmin))
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnResetAdmin))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tbdLogin.addTab("     Admin Login     ", pnlAdmin);

        pnlStaff.setAutoscrolls(true);

        lblUserNameStaff.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblUserNameStaff.setText("User_ID:");

        lblPasswordStaff.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblPasswordStaff.setText("Password:");

        txtUserNameStaff.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        txtPasswordStaff.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        btnLoginStaff.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnLoginStaff.setText("Login");
        btnLoginStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginStaffActionPerformed(evt);
            }
        });

        btnResetStaff.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnResetStaff.setText("Reset");
        btnResetStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetStaffActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor_project_ii/login_background.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblUserNameStaff)
                .addGap(18, 18, 18)
                .addComponent(txtUserNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnLoginStaff)
                .addGap(100, 100, 100)
                .addComponent(btnResetStaff))
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(txtPasswordStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblPasswordStaff))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStaffLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblUserNameStaff))
                    .addComponent(txtUserNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoginStaff)
                    .addComponent(btnResetStaff)))
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(txtPasswordStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lblPasswordStaff))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tbdLogin.addTab("     Staff Login     ", pnlStaff);

        pnlStudent.setAutoscrolls(true);

        lblUserNameStudent.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblUserNameStudent.setText("User_ID:");

        lblPasswordStudent.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblPasswordStudent.setText("Password:");

        txtUserNameStudent.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        txtPasswordStudent.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        btnLoginStudent.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnLoginStudent.setText("Login");
        btnLoginStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginStudentActionPerformed(evt);
            }
        });

        btnResetStudent.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnResetStudent.setText("Reset");
        btnResetStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetStudentActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minor_project_ii/login_background.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout pnlStudentLayout = new javax.swing.GroupLayout(pnlStudent);
        pnlStudent.setLayout(pnlStudentLayout);
        pnlStudentLayout.setHorizontalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblPasswordStudent)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnResetStudent))
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnLoginStudent))
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblUserNameStudent))
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(txtUserNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlStudentLayout.setVerticalGroup(
            pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(pnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudentLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPasswordStudent))
                    .addComponent(txtPasswordStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnResetStudent))
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnLoginStudent))
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblUserNameStudent))
            .addGroup(pnlStudentLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txtUserNameStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tbdLogin.addTab("     Student Login     ", pnlStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdLogin)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdLogin)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetStudentActionPerformed
        txtUserNameStudent.setText("");
        txtPasswordStudent.setText("");
        txtUserNameStudent.grabFocus();
    }//GEN-LAST:event_btnResetStudentActionPerformed

    private void btnResetStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetStaffActionPerformed
        txtUserNameStaff.setText("");
        txtPasswordStaff.setText("");
        txtUserNameStaff.grabFocus();
    }//GEN-LAST:event_btnResetStaffActionPerformed

    private void btnResetAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAdminActionPerformed
        txtUserNameAdmin.setText("");
        txtPasswordAdmin.setText("");
        txtUserNameAdmin.grabFocus();
    }//GEN-LAST:event_btnResetAdminActionPerformed

    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
        if (new DataSource().checkCredential(txtUserNameAdmin.getText(), txtPasswordAdmin.getPassword(), "Admin")) {
            JOptionPane.showMessageDialog(this, "Login Successful...");
            new Admin().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Login Unsuccessful...");
            btnResetAdminActionPerformed(evt);
        }
    }//GEN-LAST:event_btnLoginAdminActionPerformed

    private void btnLoginStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginStaffActionPerformed
        if (new DataSource().checkCredential(txtUserNameStaff.getText(), txtPasswordStaff.getPassword(), "Staff")) {
            JOptionPane.showMessageDialog(this, "Login Successful...");
            Staff staff = new Staff();
            staff.viewProfile(txtUserNameStaff.getText());
            staff.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Login Unsuccessful...");
            btnResetStaffActionPerformed(evt);
        }
    }//GEN-LAST:event_btnLoginStaffActionPerformed

    private void btnLoginStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginStudentActionPerformed
        if (new DataSource().checkCredential(txtUserNameStudent.getText(), txtPasswordStudent.getPassword(), "Student")) {
            JOptionPane.showMessageDialog(this, "Login Successful...");
            Student student = new Student();
            student.viewProfile(txtUserNameStudent.getText());
            student.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Login Unsuccessful...");
            btnResetStudentActionPerformed(evt);
        }
    }//GEN-LAST:event_btnLoginStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (javax.swing.UnsupportedLookAndFeelException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JButton btnLoginStaff;
    private javax.swing.JButton btnLoginStudent;
    private javax.swing.JButton btnResetAdmin;
    private javax.swing.JButton btnResetStaff;
    private javax.swing.JButton btnResetStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPasswordAdmin;
    private javax.swing.JLabel lblPasswordStaff;
    private javax.swing.JLabel lblPasswordStudent;
    private javax.swing.JLabel lblUserNameAdmin;
    private javax.swing.JLabel lblUserNameStaff;
    private javax.swing.JLabel lblUserNameStudent;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JPanel pnlStudent;
    private javax.swing.JTabbedPane tbdLogin;
    private javax.swing.JPasswordField txtPasswordAdmin;
    private javax.swing.JPasswordField txtPasswordStaff;
    private javax.swing.JPasswordField txtPasswordStudent;
    private javax.swing.JTextField txtUserNameAdmin;
    private javax.swing.JTextField txtUserNameStaff;
    private javax.swing.JTextField txtUserNameStudent;
    // End of variables declaration//GEN-END:variables
}
