/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor_project_ii;

import javax.swing.JTable;

/**
 *
 * @author vaibhav
 */
public class Staff extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Staff
     */
    java.awt.CardLayout cardLayoutManageLogbook;
    DataSource dataSource = new DataSource();

    public Staff() {
        initComponents();
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("staff.png")));
        cardLayoutManageLogbook = (java.awt.CardLayout) (pnlManageLogbookRight.getLayout());

        Thread t = new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdStaff = new javax.swing.JTabbedPane();
        pnlViewProfileStaff = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStaffViewProfileFirstName = new javax.swing.JTextField();
        txtStaffViewProfileID = new javax.swing.JTextField();
        txtStaffViewProfilePhoneNo = new javax.swing.JTextField();
        txtStaffViewProfileAddress = new javax.swing.JTextField();
        txtStaffViewProfileDepartment = new javax.swing.JTextField();
        txtStaffViewProfileLastName = new javax.swing.JTextField();
        txtStaffViewProfilePassword = new javax.swing.JTextField();
        txtStaffViewProfileEmailId = new javax.swing.JTextField();
        txtStaffViewProfileRoomAlloted = new javax.swing.JTextField();
        pnlRequestUpdateStaff = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtRequestUpdateSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRequestUpdateRequest = new javax.swing.JTextArea();
        btnRequestUpdateSend = new javax.swing.JButton();
        btnRequestUpdateReset = new javax.swing.JButton();
        pnlManageLogbook = new javax.swing.JSplitPane();
        pnlManageLogbookLeft = new javax.swing.JPanel();
        btnAddLog = new javax.swing.JButton();
        btnViewLog = new javax.swing.JButton();
        btnSearchLog = new javax.swing.JButton();
        pnlManageLogbookRight = new javax.swing.JPanel();
        pnlAddLog = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtAddLogFirstName = new javax.swing.JTextField();
        txtAddLogLastName = new javax.swing.JTextField();
        txtAddLogNoOfVisitor = new javax.swing.JTextField();
        txtAddLogPersonToMeet = new javax.swing.JTextField();
        txtAddLogAddress = new javax.swing.JTextField();
        txtAddLogPhoneNo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddLogPurposeOfVisit = new javax.swing.JTextArea();
        btnAddLogAdd = new javax.swing.JButton();
        btnAddLogReset = new javax.swing.JButton();
        txtAddLogTime = new javax.swing.JLabel();
        pnlViewLog = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblViewLog = new javax.swing.JTable();
        pnlSearchLog = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtSearchLogFirstName = new javax.swing.JTextField();
        txtSearchLogLastName = new javax.swing.JTextField();
        dtSearchLog = new com.toedter.calendar.JDateChooser();
        btnSearchLogSearch = new javax.swing.JButton();
        btnSearchLogReset = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSearchLog = new javax.swing.JTable();
        pnlSearchStaff = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtSearchStaffId = new javax.swing.JTextField();
        txtSearchStaffFirstName = new javax.swing.JTextField();
        txtSearchStaffLastName = new javax.swing.JTextField();
        btnSearchStaffSearch = new javax.swing.JButton();
        btnSearchStaffReset = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSearchStaff = new javax.swing.JTable();
        pnlSearchStudent = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtSearchStudentId = new javax.swing.JTextField();
        txtSearchStudentFirstName = new javax.swing.JTextField();
        txtSearchStudentLastName = new javax.swing.JTextField();
        btnSearchStudentSearch = new javax.swing.JButton();
        btnSearchStudentReset = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSearchStudent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STAFF");
        setResizable(false);

        tbdStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbdStaff.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tbdStaff.setMinimumSize(new java.awt.Dimension(150, 344));

        pnlViewProfileStaff.setBackground(new java.awt.Color(64, 224, 208));

        jPanel1.setBackground(new java.awt.Color(64, 224, 208));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  View Profile  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("ID:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Phone Number:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Address:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Department:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Last Name:");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Password:");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Email Id:");

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Room Allotted:");

        txtStaffViewProfileFirstName.setEditable(false);
        txtStaffViewProfileFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStaffViewProfileID.setEditable(false);
        txtStaffViewProfileID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStaffViewProfilePhoneNo.setEditable(false);
        txtStaffViewProfilePhoneNo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStaffViewProfileAddress.setEditable(false);
        txtStaffViewProfileAddress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStaffViewProfileDepartment.setEditable(false);
        txtStaffViewProfileDepartment.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStaffViewProfileLastName.setEditable(false);
        txtStaffViewProfileLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStaffViewProfilePassword.setEditable(false);
        txtStaffViewProfilePassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStaffViewProfileEmailId.setEditable(false);
        txtStaffViewProfileEmailId.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStaffViewProfileRoomAlloted.setEditable(false);
        txtStaffViewProfileRoomAlloted.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStaffViewProfileDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtStaffViewProfileFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtStaffViewProfileID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStaffViewProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStaffViewProfilePhoneNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtStaffViewProfilePassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtStaffViewProfileEmailId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaffViewProfileRoomAlloted, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStaffViewProfileLastName))))
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(txtStaffViewProfileFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffViewProfileLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(txtStaffViewProfileID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffViewProfilePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtStaffViewProfilePhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffViewProfileEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtStaffViewProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStaffViewProfileRoomAlloted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStaffViewProfileDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlViewProfileStaffLayout = new javax.swing.GroupLayout(pnlViewProfileStaff);
        pnlViewProfileStaff.setLayout(pnlViewProfileStaffLayout);
        pnlViewProfileStaffLayout.setHorizontalGroup(
            pnlViewProfileStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewProfileStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlViewProfileStaffLayout.setVerticalGroup(
            pnlViewProfileStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewProfileStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdStaff.addTab("     View Profile     ", pnlViewProfileStaff);

        pnlRequestUpdateStaff.setBackground(new java.awt.Color(64, 224, 208));

        jPanel2.setBackground(new java.awt.Color(64, 224, 208));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  Request Changes  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Enter Subject:");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("Enter Request:");

        txtRequestUpdateSubject.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtRequestUpdateRequest.setColumns(20);
        txtRequestUpdateRequest.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtRequestUpdateRequest.setLineWrap(true);
        txtRequestUpdateRequest.setRows(5);
        jScrollPane1.setViewportView(txtRequestUpdateRequest);

        btnRequestUpdateSend.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRequestUpdateSend.setText("Send Request");
        btnRequestUpdateSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestUpdateSendActionPerformed(evt);
            }
        });

        btnRequestUpdateReset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRequestUpdateReset.setText("Reset");
        btnRequestUpdateReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestUpdateResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRequestUpdateSubject)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnRequestUpdateSend)
                        .addGap(176, 176, 176)
                        .addComponent(btnRequestUpdateReset)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRequestUpdateSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestUpdateSend)
                    .addComponent(btnRequestUpdateReset))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRequestUpdateStaffLayout = new javax.swing.GroupLayout(pnlRequestUpdateStaff);
        pnlRequestUpdateStaff.setLayout(pnlRequestUpdateStaffLayout);
        pnlRequestUpdateStaffLayout.setHorizontalGroup(
            pnlRequestUpdateStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestUpdateStaffLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRequestUpdateStaffLayout.setVerticalGroup(
            pnlRequestUpdateStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRequestUpdateStaffLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        tbdStaff.addTab("     Request Changes     ", pnlRequestUpdateStaff);

        pnlManageLogbookLeft.setMinimumSize(new java.awt.Dimension(150, 100));
        pnlManageLogbookLeft.setPreferredSize(new java.awt.Dimension(150, 459));

        btnAddLog.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAddLog.setText("Add Log");
        btnAddLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLogActionPerformed(evt);
            }
        });

        btnViewLog.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnViewLog.setText("View Log");
        btnViewLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLogActionPerformed(evt);
            }
        });

        btnSearchLog.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchLog.setText("Search Log");
        btnSearchLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManageLogbookLeftLayout = new javax.swing.GroupLayout(pnlManageLogbookLeft);
        pnlManageLogbookLeft.setLayout(pnlManageLogbookLeftLayout);
        pnlManageLogbookLeftLayout.setHorizontalGroup(
            pnlManageLogbookLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageLogbookLeftLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlManageLogbookLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchLog)
                    .addComponent(btnViewLog, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddLog, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnlManageLogbookLeftLayout.setVerticalGroup(
            pnlManageLogbookLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageLogbookLeftLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnAddLog)
                .addGap(65, 65, 65)
                .addComponent(btnViewLog)
                .addGap(65, 65, 65)
                .addComponent(btnSearchLog)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pnlManageLogbook.setLeftComponent(pnlManageLogbookLeft);

        pnlManageLogbookRight.setLayout(new java.awt.CardLayout());

        pnlAddLog.setBackground(new java.awt.Color(64, 224, 208));

        jPanel3.setBackground(new java.awt.Color(64, 224, 208));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  Add Log  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("First Name of visitor:");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Last Name of visitor:");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Purpose of visit:");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Person to meet:");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setText("Address of visitor:");

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel17.setText("Phone No of visitor:");

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel18.setText("Date and Time:");

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel19.setText("Total Number of visitor:");

        txtAddLogFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAddLogFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddLogFirstNameKeyPressed(evt);
            }
        });

        txtAddLogLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAddLogLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddLogLastNameKeyPressed(evt);
            }
        });

        txtAddLogNoOfVisitor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAddLogNoOfVisitor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddLogNoOfVisitorKeyPressed(evt);
            }
        });

        txtAddLogPersonToMeet.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAddLogPersonToMeet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddLogPersonToMeetKeyPressed(evt);
            }
        });

        txtAddLogAddress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtAddLogPhoneNo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAddLogPhoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddLogPhoneNoKeyPressed(evt);
            }
        });

        txtAddLogPurposeOfVisit.setColumns(20);
        txtAddLogPurposeOfVisit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAddLogPurposeOfVisit.setLineWrap(true);
        txtAddLogPurposeOfVisit.setRows(5);
        jScrollPane2.setViewportView(txtAddLogPurposeOfVisit);

        btnAddLogAdd.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAddLogAdd.setText("Add Log");
        btnAddLogAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLogAddActionPerformed(evt);
            }
        });

        btnAddLogReset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAddLogReset.setText("Reset");
        btnAddLogReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLogResetActionPerformed(evt);
            }
        });

        txtAddLogTime.setBackground(new java.awt.Color(255, 255, 255));
        txtAddLogTime.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAddLogAddress)
                            .addComponent(txtAddLogFirstName)
                            .addComponent(txtAddLogNoOfVisitor)
                            .addComponent(txtAddLogTime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAddLogReset)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAddLogLastName)
                            .addComponent(txtAddLogPersonToMeet)
                            .addComponent(txtAddLogPhoneNo)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnAddLogAdd)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtAddLogFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtAddLogLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAddLogPersonToMeet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtAddLogNoOfVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(txtAddLogAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddLogPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAddLogTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLogAdd)
                    .addComponent(btnAddLogReset))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAddLogLayout = new javax.swing.GroupLayout(pnlAddLog);
        pnlAddLog.setLayout(pnlAddLogLayout);
        pnlAddLogLayout.setHorizontalGroup(
            pnlAddLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAddLogLayout.setVerticalGroup(
            pnlAddLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlManageLogbookRight.add(pnlAddLog, "pnlAddLog");

        pnlViewLog.setBackground(new java.awt.Color(64, 224, 208));

        jPanel5.setBackground(new java.awt.Color(64, 224, 208));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  View Log  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        tblViewLog.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tblViewLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Total Visitor", "Date", "Time", "Person to Meet", "Purpose of Meeting", "Address", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewLog.setRowHeight(26);
        tblViewLog.setRowMargin(0);
        jScrollPane3.setViewportView(tblViewLog);
        tblViewLog.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        if (tblViewLog.getColumnModel().getColumnCount() > 0) {
            tblViewLog.getColumnModel().getColumn(0).setMinWidth(80);
            tblViewLog.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblViewLog.getColumnModel().getColumn(0).setMaxWidth(160);
            tblViewLog.getColumnModel().getColumn(1).setMinWidth(80);
            tblViewLog.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblViewLog.getColumnModel().getColumn(1).setMaxWidth(160);
            tblViewLog.getColumnModel().getColumn(2).setMinWidth(50);
            tblViewLog.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblViewLog.getColumnModel().getColumn(2).setMaxWidth(100);
            tblViewLog.getColumnModel().getColumn(3).setMinWidth(50);
            tblViewLog.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblViewLog.getColumnModel().getColumn(3).setMaxWidth(150);
            tblViewLog.getColumnModel().getColumn(4).setMinWidth(50);
            tblViewLog.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblViewLog.getColumnModel().getColumn(4).setMaxWidth(150);
            tblViewLog.getColumnModel().getColumn(5).setMinWidth(120);
            tblViewLog.getColumnModel().getColumn(5).setPreferredWidth(120);
            tblViewLog.getColumnModel().getColumn(5).setMaxWidth(200);
            tblViewLog.getColumnModel().getColumn(6).setMinWidth(300);
            tblViewLog.getColumnModel().getColumn(6).setPreferredWidth(400);
            tblViewLog.getColumnModel().getColumn(6).setMaxWidth(500);
            tblViewLog.getColumnModel().getColumn(7).setMinWidth(200);
            tblViewLog.getColumnModel().getColumn(7).setPreferredWidth(250);
            tblViewLog.getColumnModel().getColumn(7).setMaxWidth(400);
            tblViewLog.getColumnModel().getColumn(8).setMinWidth(100);
            tblViewLog.getColumnModel().getColumn(8).setPreferredWidth(100);
            tblViewLog.getColumnModel().getColumn(8).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlViewLogLayout = new javax.swing.GroupLayout(pnlViewLog);
        pnlViewLog.setLayout(pnlViewLogLayout);
        pnlViewLogLayout.setHorizontalGroup(
            pnlViewLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(pnlViewLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewLogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlViewLogLayout.setVerticalGroup(
            pnlViewLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(pnlViewLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlViewLogLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pnlManageLogbookRight.add(pnlViewLog, "pnlViewLog");

        pnlSearchLog.setBackground(new java.awt.Color(64, 224, 208));

        jPanel4.setBackground(new java.awt.Color(64, 224, 208));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  Search Log  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel20.setText("Enter First Name:");

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel21.setText("Enter Last Name:");

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel22.setText("Choose Date:");

        txtSearchLogFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtSearchLogLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        dtSearchLog.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnSearchLogSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchLogSearch.setText("Search Log");
        btnSearchLogSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLogSearchActionPerformed(evt);
            }
        });

        btnSearchLogReset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchLogReset.setText("Reset");
        btnSearchLogReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLogResetActionPerformed(evt);
            }
        });

        tblSearchLog.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tblSearchLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Total Visitor", "Date", "Time", "Person to Meet", "Purpose of Meeting", "Address", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchLog.setRowHeight(26);
        tblSearchLog.setRowMargin(0);
        jScrollPane4.setViewportView(tblSearchLog);
        if (tblSearchLog.getColumnModel().getColumnCount() > 0) {
            tblSearchLog.getColumnModel().getColumn(0).setMinWidth(80);
            tblSearchLog.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblSearchLog.getColumnModel().getColumn(0).setMaxWidth(160);
            tblSearchLog.getColumnModel().getColumn(1).setMinWidth(80);
            tblSearchLog.getColumnModel().getColumn(1).setPreferredWidth(80);
            tblSearchLog.getColumnModel().getColumn(1).setMaxWidth(160);
            tblSearchLog.getColumnModel().getColumn(2).setMinWidth(50);
            tblSearchLog.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblSearchLog.getColumnModel().getColumn(2).setMaxWidth(100);
            tblSearchLog.getColumnModel().getColumn(3).setMinWidth(50);
            tblSearchLog.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblSearchLog.getColumnModel().getColumn(3).setMaxWidth(150);
            tblSearchLog.getColumnModel().getColumn(4).setMinWidth(50);
            tblSearchLog.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblSearchLog.getColumnModel().getColumn(4).setMaxWidth(150);
            tblSearchLog.getColumnModel().getColumn(5).setMinWidth(120);
            tblSearchLog.getColumnModel().getColumn(5).setPreferredWidth(120);
            tblSearchLog.getColumnModel().getColumn(5).setMaxWidth(200);
            tblSearchLog.getColumnModel().getColumn(6).setMinWidth(300);
            tblSearchLog.getColumnModel().getColumn(6).setPreferredWidth(400);
            tblSearchLog.getColumnModel().getColumn(6).setMaxWidth(500);
            tblSearchLog.getColumnModel().getColumn(7).setMinWidth(200);
            tblSearchLog.getColumnModel().getColumn(7).setPreferredWidth(250);
            tblSearchLog.getColumnModel().getColumn(7).setMaxWidth(400);
            tblSearchLog.getColumnModel().getColumn(8).setMinWidth(100);
            tblSearchLog.getColumnModel().getColumn(8).setPreferredWidth(100);
            tblSearchLog.getColumnModel().getColumn(8).setMaxWidth(150);
        }
        tblSearchLog.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSearchLogSearch)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchLogFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(btnSearchLogReset))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchLogLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtSearchLog, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtSearchLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(txtSearchLogFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(txtSearchLogLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchLogSearch)
                    .addComponent(btnSearchLogReset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSearchLogLayout = new javax.swing.GroupLayout(pnlSearchLog);
        pnlSearchLog.setLayout(pnlSearchLogLayout);
        pnlSearchLogLayout.setHorizontalGroup(
            pnlSearchLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        pnlSearchLogLayout.setVerticalGroup(
            pnlSearchLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlManageLogbookRight.add(pnlSearchLog, "pnlSearchLog");

        pnlManageLogbook.setRightComponent(pnlManageLogbookRight);

        tbdStaff.addTab("     Manange Logbook     ", pnlManageLogbook);

        pnlSearchStaff.setBackground(new java.awt.Color(64, 224, 208));

        jPanel6.setBackground(new java.awt.Color(64, 224, 208));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  Search Staff  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel23.setText("Enter ID:");

        jLabel24.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel24.setText("Enter First Name:");

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel25.setText("Enter Last Name:");

        txtSearchStaffId.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtSearchStaffFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtSearchStaffLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnSearchStaffSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchStaffSearch.setText("Search Staff");
        btnSearchStaffSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStaffSearchActionPerformed(evt);
            }
        });

        btnSearchStaffReset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchStaffReset.setText("Reset");
        btnSearchStaffReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStaffResetActionPerformed(evt);
            }
        });

        tblSearchStaff.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tblSearchStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "First Name", "Last Name", "Phone Number", "Email ID", "Room Allotted", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchStaff.setRowHeight(26);
        jScrollPane5.setViewportView(tblSearchStaff);
        if (tblSearchStaff.getColumnModel().getColumnCount() > 0) {
            tblSearchStaff.getColumnModel().getColumn(0).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(0).setPreferredWidth(110);
            tblSearchStaff.getColumnModel().getColumn(0).setMaxWidth(150);
            tblSearchStaff.getColumnModel().getColumn(1).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(1).setPreferredWidth(110);
            tblSearchStaff.getColumnModel().getColumn(1).setMaxWidth(150);
            tblSearchStaff.getColumnModel().getColumn(2).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(2).setPreferredWidth(110);
            tblSearchStaff.getColumnModel().getColumn(2).setMaxWidth(150);
            tblSearchStaff.getColumnModel().getColumn(3).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblSearchStaff.getColumnModel().getColumn(3).setMaxWidth(150);
            tblSearchStaff.getColumnModel().getColumn(4).setMinWidth(250);
            tblSearchStaff.getColumnModel().getColumn(4).setPreferredWidth(270);
            tblSearchStaff.getColumnModel().getColumn(4).setMaxWidth(320);
            tblSearchStaff.getColumnModel().getColumn(5).setMinWidth(70);
            tblSearchStaff.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblSearchStaff.getColumnModel().getColumn(5).setMaxWidth(130);
            tblSearchStaff.getColumnModel().getColumn(6).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblSearchStaff.getColumnModel().getColumn(6).setMaxWidth(130);
        }
        tblSearchStaff.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearchStaffFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(btnSearchStaffSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchStaffReset)))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchStaffLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtSearchStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtSearchStaffFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtSearchStaffLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchStaffSearch)
                    .addComponent(btnSearchStaffReset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSearchStaffLayout = new javax.swing.GroupLayout(pnlSearchStaff);
        pnlSearchStaff.setLayout(pnlSearchStaffLayout);
        pnlSearchStaffLayout.setHorizontalGroup(
            pnlSearchStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchStaffLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlSearchStaffLayout.setVerticalGroup(
            pnlSearchStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdStaff.addTab("     Search Staff     ", pnlSearchStaff);

        pnlSearchStudent.setBackground(new java.awt.Color(64, 224, 208));

        jPanel7.setBackground(new java.awt.Color(64, 224, 208));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  Search Student  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel35.setText("Enter Id:");

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel36.setText("Enter First Name:");

        jLabel37.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel37.setText("Enter Last Name:");

        txtSearchStudentId.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtSearchStudentFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtSearchStudentLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnSearchStudentSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchStudentSearch.setText("Search");
        btnSearchStudentSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentSearchActionPerformed(evt);
            }
        });

        btnSearchStudentReset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchStudentReset.setText("Reset");
        btnSearchStudentReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudentResetActionPerformed(evt);
            }
        });

        tblSearchStudent.setAutoCreateRowSorter(true);
        tblSearchStudent.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tblSearchStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "First Name", "Last Name", "Course", "Room Alloted", "Password", "Phone Number", "Email Id", "Parent's Phone Number", "Parent's Email Id", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchStudent.setRowHeight(26);
        tblSearchStudent.setRowMargin(0);
        tblSearchStudent.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tblSearchStudent);
        if (tblSearchStudent.getColumnModel().getColumnCount() > 0) {
            tblSearchStudent.getColumnModel().getColumn(0).setMinWidth(100);
            tblSearchStudent.getColumnModel().getColumn(1).setMinWidth(100);
            tblSearchStudent.getColumnModel().getColumn(2).setMinWidth(100);
            tblSearchStudent.getColumnModel().getColumn(3).setMinWidth(100);
            tblSearchStudent.getColumnModel().getColumn(4).setMinWidth(100);
            tblSearchStudent.getColumnModel().getColumn(5).setMinWidth(100);
            tblSearchStudent.getColumnModel().getColumn(6).setMinWidth(100);
            tblSearchStudent.getColumnModel().getColumn(7).setMinWidth(200);
            tblSearchStudent.getColumnModel().getColumn(8).setMinWidth(100);
            tblSearchStudent.getColumnModel().getColumn(9).setMinWidth(200);
            tblSearchStudent.getColumnModel().getColumn(10).setMinWidth(250);
        }
        tblSearchStudent.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(btnSearchStudentSearch)
                .addGap(220, 220, 220)
                .addComponent(btnSearchStudentReset))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel37)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(txtSearchStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchStudentSearch)
                    .addComponent(btnSearchStudentReset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSearchStudentLayout = new javax.swing.GroupLayout(pnlSearchStudent);
        pnlSearchStudent.setLayout(pnlSearchStudentLayout);
        pnlSearchStudentLayout.setHorizontalGroup(
            pnlSearchStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlSearchStudentLayout.setVerticalGroup(
            pnlSearchStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdStaff.addTab("     Search Student     ", pnlSearchStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tbdStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestUpdateResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestUpdateResetActionPerformed
        txtRequestUpdateSubject.setText("");
        txtRequestUpdateRequest.setText("");
        txtRequestUpdateSubject.grabFocus();
    }//GEN-LAST:event_btnRequestUpdateResetActionPerformed

    private void btnRequestUpdateSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestUpdateSendActionPerformed
        // this method is common in both staff and student, the body of this method is in student related database queries
        dataSource.updateRequest(txtRequestUpdateSubject, txtRequestUpdateRequest, staffId, "Staff");
    }//GEN-LAST:event_btnRequestUpdateSendActionPerformed

    private void btnAddLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLogActionPerformed
        cardLayoutManageLogbook.show(pnlManageLogbookRight, "pnlAddLog");
    }//GEN-LAST:event_btnAddLogActionPerformed

    private void btnViewLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLogActionPerformed
        cardLayoutManageLogbook.show(pnlManageLogbookRight, "pnlViewLog");
        dataSource.viewLogbook(tblViewLog);
    }//GEN-LAST:event_btnViewLogActionPerformed

    private void btnSearchLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLogActionPerformed
        cardLayoutManageLogbook.show(pnlManageLogbookRight, "pnlSearchLog");
    }//GEN-LAST:event_btnSearchLogActionPerformed

    private void btnAddLogResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLogResetActionPerformed
        txtAddLogFirstName.setText("");
        txtAddLogLastName.setText("");
        txtAddLogNoOfVisitor.setText("");
        txtAddLogAddress.setText("");
        txtAddLogPersonToMeet.setText("");
        txtAddLogPhoneNo.setText("");
        txtAddLogPurposeOfVisit.setText("");
    }//GEN-LAST:event_btnAddLogResetActionPerformed

    private void txtAddLogPhoneNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddLogPhoneNoKeyPressed
        dataSource.onlyInt(txtAddLogPhoneNo, 10, evt);
    }//GEN-LAST:event_txtAddLogPhoneNoKeyPressed

    private void txtAddLogNoOfVisitorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddLogNoOfVisitorKeyPressed
        dataSource.onlyInt(txtAddLogNoOfVisitor, 2, evt);
    }//GEN-LAST:event_txtAddLogNoOfVisitorKeyPressed

    private void txtAddLogFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddLogFirstNameKeyPressed
        dataSource.onlyChar(txtAddLogFirstName, evt);
    }//GEN-LAST:event_txtAddLogFirstNameKeyPressed

    private void txtAddLogLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddLogLastNameKeyPressed
        dataSource.onlyChar(txtAddLogLastName, evt);
    }//GEN-LAST:event_txtAddLogLastNameKeyPressed

    private void txtAddLogPersonToMeetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddLogPersonToMeetKeyPressed
        dataSource.onlyChar(txtAddLogPersonToMeet, evt);
    }//GEN-LAST:event_txtAddLogPersonToMeetKeyPressed

    private void btnAddLogAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLogAddActionPerformed
        Object object[] = {
            txtAddLogFirstName.getText(), txtAddLogLastName.getText(), txtAddLogNoOfVisitor.getText(), txtAddLogPersonToMeet.getText(),
            txtAddLogAddress.getText(), txtAddLogPhoneNo.getText(), txtAddLogPurposeOfVisit.getText()};
        dataSource.addLog(object);
        btnAddLogResetActionPerformed(evt);
    }//GEN-LAST:event_btnAddLogAddActionPerformed

    private void btnSearchLogResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLogResetActionPerformed
        txtSearchLogFirstName.setText("");
        txtSearchLogLastName.setText("");
        dtSearchLog.setDate(null);
    }//GEN-LAST:event_btnSearchLogResetActionPerformed

    private void btnSearchLogSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLogSearchActionPerformed
        java.util.Date date = dtSearchLog.getDate();
        dataSource.searchLogbook(tblSearchLog, txtSearchLogFirstName.getText(), txtSearchLogLastName.getText(), date);
    }//GEN-LAST:event_btnSearchLogSearchActionPerformed

    private void btnSearchStaffResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStaffResetActionPerformed
        txtSearchStaffId.setText("");
        txtSearchStaffFirstName.setText("");
        txtSearchStaffLastName.setText("");
    }//GEN-LAST:event_btnSearchStaffResetActionPerformed

    private void btnSearchStaffSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStaffSearchActionPerformed
        dataSource.searchStaffContact(txtSearchStaffFirstName.getText(), txtSearchStaffLastName.getText(), txtSearchStaffId.getText(), tblSearchStaff);
    }//GEN-LAST:event_btnSearchStaffSearchActionPerformed

    private void btnSearchStudentSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentSearchActionPerformed
        dataSource.searchStudent(txtSearchStudentId.getText(), txtSearchStudentFirstName.getText(), txtSearchStudentLastName.getText(), tblSearchStudent);
    }//GEN-LAST:event_btnSearchStudentSearchActionPerformed

    private void btnSearchStudentResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudentResetActionPerformed
        txtSearchStudentId.setText("");
        txtSearchStudentFirstName.setText("");
        txtSearchStudentLastName.setText("");
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSearchStudent.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnSearchStudentResetActionPerformed

    String staffId;

    public void viewProfile(String id) {
        staffId = id;
        Object profile[] = (Object[]) dataSource.viewProfileStaff(id);
        txtStaffViewProfileID.setText(profile[0].toString());
        txtStaffViewProfileFirstName.setText(profile[1].toString());
        txtStaffViewProfileLastName.setText(profile[2].toString());
        txtStaffViewProfileRoomAlloted.setText(profile[3].toString());
        txtStaffViewProfilePhoneNo.setText(profile[4].toString());
        txtStaffViewProfileEmailId.setText(profile[5].toString());
        txtStaffViewProfileDepartment.setText(profile[6].toString());
        txtStaffViewProfilePassword.setText(profile[7].toString());
        txtStaffViewProfileAddress.setText(profile[8].toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Staff().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLog;
    private javax.swing.JButton btnAddLogAdd;
    private javax.swing.JButton btnAddLogReset;
    private javax.swing.JButton btnRequestUpdateReset;
    private javax.swing.JButton btnRequestUpdateSend;
    private javax.swing.JButton btnSearchLog;
    private javax.swing.JButton btnSearchLogReset;
    private javax.swing.JButton btnSearchLogSearch;
    private javax.swing.JButton btnSearchStaffReset;
    private javax.swing.JButton btnSearchStaffSearch;
    private javax.swing.JButton btnSearchStudentReset;
    private javax.swing.JButton btnSearchStudentSearch;
    private javax.swing.JButton btnViewLog;
    private com.toedter.calendar.JDateChooser dtSearchLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel pnlAddLog;
    private javax.swing.JSplitPane pnlManageLogbook;
    private javax.swing.JPanel pnlManageLogbookLeft;
    private javax.swing.JPanel pnlManageLogbookRight;
    private javax.swing.JPanel pnlRequestUpdateStaff;
    private javax.swing.JPanel pnlSearchLog;
    private javax.swing.JPanel pnlSearchStaff;
    private javax.swing.JPanel pnlSearchStudent;
    private javax.swing.JPanel pnlViewLog;
    private javax.swing.JPanel pnlViewProfileStaff;
    private javax.swing.JTabbedPane tbdStaff;
    private javax.swing.JTable tblSearchLog;
    private javax.swing.JTable tblSearchStaff;
    private javax.swing.JTable tblSearchStudent;
    private javax.swing.JTable tblViewLog;
    private javax.swing.JTextField txtAddLogAddress;
    private javax.swing.JTextField txtAddLogFirstName;
    private javax.swing.JTextField txtAddLogLastName;
    private javax.swing.JTextField txtAddLogNoOfVisitor;
    private javax.swing.JTextField txtAddLogPersonToMeet;
    private javax.swing.JTextField txtAddLogPhoneNo;
    private javax.swing.JTextArea txtAddLogPurposeOfVisit;
    private javax.swing.JLabel txtAddLogTime;
    private javax.swing.JTextArea txtRequestUpdateRequest;
    private javax.swing.JTextField txtRequestUpdateSubject;
    private javax.swing.JTextField txtSearchLogFirstName;
    private javax.swing.JTextField txtSearchLogLastName;
    private javax.swing.JTextField txtSearchStaffFirstName;
    private javax.swing.JTextField txtSearchStaffId;
    private javax.swing.JTextField txtSearchStaffLastName;
    private javax.swing.JTextField txtSearchStudentFirstName;
    private javax.swing.JTextField txtSearchStudentId;
    private javax.swing.JTextField txtSearchStudentLastName;
    private javax.swing.JTextField txtStaffViewProfileAddress;
    private javax.swing.JTextField txtStaffViewProfileDepartment;
    private javax.swing.JTextField txtStaffViewProfileEmailId;
    private javax.swing.JTextField txtStaffViewProfileFirstName;
    private javax.swing.JTextField txtStaffViewProfileID;
    private javax.swing.JTextField txtStaffViewProfileLastName;
    private javax.swing.JTextField txtStaffViewProfilePassword;
    private javax.swing.JTextField txtStaffViewProfilePhoneNo;
    private javax.swing.JTextField txtStaffViewProfileRoomAlloted;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        // to fetch the system date
        while (true) {
            try {
                java.text.DateFormat df = new java.text.SimpleDateFormat("dd/MM/yyyy      hh:mm:ss a");
                java.util.Date dateobj = new java.util.Date();
                txtAddLogTime.setText(df.format(dateobj.getTime()));
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Something went wrong: " + e.getMessage());
            }
        }
    }
}
