/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minor_project_ii;

import javax.swing.JTable;

/**
 *
 * @author vaibhav
 */
public class Student extends javax.swing.JFrame {

    DataSource dataSource = new DataSource();

    /**
     * Creates new form Student
     */
    public Student() {
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("student.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdStudent = new javax.swing.JTabbedPane();
        pnlViewProfile = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtStudentViewProfileParentPhoneNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStudentViewProfilePassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentViewProfileEmailID = new javax.swing.JTextField();
        txtStudentViewProfileID = new javax.swing.JTextField();
        txtStudentViewProfileCourse = new javax.swing.JTextField();
        txtStudentViewProfileParentEmailID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStudentViewProfilePhoneNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStudentViewProfileLastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtStudentViewProfileAddress = new javax.swing.JTextField();
        txtStudentViewProfileFirstName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStudentViewProfileRoomAlloted = new javax.swing.JTextField();
        pnlRequestChange = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtRequestUpdateSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRequestUpdateRequest = new javax.swing.JTextArea();
        btnRequestUpdateSendRequest = new javax.swing.JButton();
        btnRequestUpdateReset = new javax.swing.JButton();
        pnlSearchStaffContact = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSearchStaffId = new javax.swing.JTextField();
        txtSearchStaffFirstName = new javax.swing.JTextField();
        txtSearchStaffLastName = new javax.swing.JTextField();
        btnSearchStaffSearch = new javax.swing.JButton();
        btnSearchStaffReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearchStaff = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT");
        setResizable(false);

        tbdStudent.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tbdStudent.setPreferredSize(new java.awt.Dimension(1008, 450));

        pnlViewProfile.setBackground(new java.awt.Color(64, 224, 208));
        pnlViewProfile.setPreferredSize(new java.awt.Dimension(849, 450));

        jPanel2.setBackground(new java.awt.Color(64, 224, 208));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  View Profile  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setText("Room Allotted:");

        txtStudentViewProfileParentPhoneNo.setEditable(false);
        txtStudentViewProfileParentPhoneNo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Phone Number:");

        txtStudentViewProfilePassword.setEditable(false);
        txtStudentViewProfilePassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Email ID:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Password:");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("First Name:");

        txtStudentViewProfileEmailID.setEditable(false);
        txtStudentViewProfileEmailID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStudentViewProfileID.setEditable(false);
        txtStudentViewProfileID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStudentViewProfileCourse.setEditable(false);
        txtStudentViewProfileCourse.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStudentViewProfileParentEmailID.setEditable(false);
        txtStudentViewProfileParentEmailID.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Parent's Phone Number:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Address:");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Last Name:");

        txtStudentViewProfilePhoneNo.setEditable(false);
        txtStudentViewProfilePhoneNo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("College ID:");

        txtStudentViewProfileLastName.setEditable(false);
        txtStudentViewProfileLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Course:");

        txtStudentViewProfileAddress.setEditable(false);
        txtStudentViewProfileAddress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtStudentViewProfileFirstName.setEditable(false);
        txtStudentViewProfileFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Parent's Email ID:");

        txtStudentViewProfileRoomAlloted.setEditable(false);
        txtStudentViewProfileRoomAlloted.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentViewProfileCourse)
                    .addComponent(txtStudentViewProfilePhoneNo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtStudentViewProfileID)
                    .addComponent(txtStudentViewProfileAddress)
                    .addComponent(txtStudentViewProfileFirstName)
                    .addComponent(txtStudentViewProfileRoomAlloted, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStudentViewProfilePassword)
                    .addComponent(txtStudentViewProfileEmailID)
                    .addComponent(txtStudentViewProfileParentEmailID)
                    .addComponent(txtStudentViewProfileParentPhoneNo)
                    .addComponent(txtStudentViewProfileLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentViewProfileFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentViewProfileLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtStudentViewProfileID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentViewProfilePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(txtStudentViewProfileAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentViewProfileEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtStudentViewProfilePhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentViewProfileParentEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(txtStudentViewProfileCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudentViewProfileParentPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtStudentViewProfileRoomAlloted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlViewProfileLayout = new javax.swing.GroupLayout(pnlViewProfile);
        pnlViewProfile.setLayout(pnlViewProfileLayout);
        pnlViewProfileLayout.setHorizontalGroup(
            pnlViewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlViewProfileLayout.setVerticalGroup(
            pnlViewProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdStudent.addTab("     View Profile     ", pnlViewProfile);

        pnlRequestChange.setBackground(new java.awt.Color(64, 224, 208));

        jPanel1.setBackground(new java.awt.Color(64, 224, 208));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  Request Changes  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Enter Subject:");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Enter Request:");

        txtRequestUpdateSubject.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtRequestUpdateRequest.setColumns(20);
        txtRequestUpdateRequest.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtRequestUpdateRequest.setLineWrap(true);
        txtRequestUpdateRequest.setRows(5);
        jScrollPane1.setViewportView(txtRequestUpdateRequest);

        btnRequestUpdateSendRequest.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRequestUpdateSendRequest.setText("Send Request");
        btnRequestUpdateSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestUpdateSendRequestActionPerformed(evt);
            }
        });

        btnRequestUpdateReset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRequestUpdateReset.setText("Reset");
        btnRequestUpdateReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestUpdateResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnRequestUpdateSendRequest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRequestUpdateReset)
                        .addGap(20, 20, 20))
                    .addComponent(txtRequestUpdateSubject)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRequestUpdateSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequestUpdateSendRequest)
                    .addComponent(btnRequestUpdateReset))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlRequestChangeLayout = new javax.swing.GroupLayout(pnlRequestChange);
        pnlRequestChange.setLayout(pnlRequestChangeLayout);
        pnlRequestChangeLayout.setHorizontalGroup(
            pnlRequestChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRequestChangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRequestChangeLayout.setVerticalGroup(
            pnlRequestChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRequestChangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdStudent.addTab("     Request Changes     ", pnlRequestChange);

        pnlSearchStaffContact.setBackground(new java.awt.Color(64, 224, 208));

        jPanel3.setBackground(new java.awt.Color(64, 224, 208));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true), "  Search Staff  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 24), new java.awt.Color(0, 153, 102))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("Enter ID:");

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel15.setText("Enter First Name:");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel16.setText("Enter Last Name:");

        txtSearchStaffId.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtSearchStaffFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        txtSearchStaffLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btnSearchStaffSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchStaffSearch.setText("Search");
        btnSearchStaffSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStaffSearchActionPerformed(evt);
            }
        });

        btnSearchStaffReset.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSearchStaffReset.setText("Reset");
        btnSearchStaffReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStaffResetActionPerformed(evt);
            }
        });

        tblSearchStaff.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tblSearchStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "ID", "Phone Number", "Email ID", "Room Allotted", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchStaff.setRowHeight(26);
        jScrollPane2.setViewportView(tblSearchStaff);
        if (tblSearchStaff.getColumnModel().getColumnCount() > 0) {
            tblSearchStaff.getColumnModel().getColumn(0).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblSearchStaff.getColumnModel().getColumn(0).setMaxWidth(130);
            tblSearchStaff.getColumnModel().getColumn(1).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblSearchStaff.getColumnModel().getColumn(1).setMaxWidth(130);
            tblSearchStaff.getColumnModel().getColumn(2).setMinWidth(60);
            tblSearchStaff.getColumnModel().getColumn(2).setPreferredWidth(95);
            tblSearchStaff.getColumnModel().getColumn(2).setMaxWidth(130);
            tblSearchStaff.getColumnModel().getColumn(3).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(3).setPreferredWidth(110);
            tblSearchStaff.getColumnModel().getColumn(3).setMaxWidth(170);
            tblSearchStaff.getColumnModel().getColumn(4).setMinWidth(200);
            tblSearchStaff.getColumnModel().getColumn(4).setPreferredWidth(250);
            tblSearchStaff.getColumnModel().getColumn(4).setMaxWidth(300);
            tblSearchStaff.getColumnModel().getColumn(5).setMinWidth(60);
            tblSearchStaff.getColumnModel().getColumn(5).setPreferredWidth(90);
            tblSearchStaff.getColumnModel().getColumn(5).setMaxWidth(150);
            tblSearchStaff.getColumnModel().getColumn(6).setMinWidth(80);
            tblSearchStaff.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblSearchStaff.getColumnModel().getColumn(6).setMaxWidth(150);
        }
        tblSearchStaff.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnSearchStaffSearch)
                        .addGap(228, 228, 228)
                        .addComponent(btnSearchStaffReset))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearchStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchStaffFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchStaffLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(txtSearchStaffId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchStaffFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchStaffLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchStaffSearch)
                    .addComponent(btnSearchStaffReset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSearchStaffContactLayout = new javax.swing.GroupLayout(pnlSearchStaffContact);
        pnlSearchStaffContact.setLayout(pnlSearchStaffContactLayout);
        pnlSearchStaffContactLayout.setHorizontalGroup(
            pnlSearchStaffContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchStaffContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 829, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSearchStaffContactLayout.setVerticalGroup(
            pnlSearchStaffContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchStaffContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbdStudent.addTab("     Search Staff Contact     ", pnlSearchStaffContact);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestUpdateSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestUpdateSendRequestActionPerformed
        dataSource.updateRequest(txtRequestUpdateSubject, txtRequestUpdateRequest, studentID, "Student");
    }//GEN-LAST:event_btnRequestUpdateSendRequestActionPerformed

    private void btnRequestUpdateResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestUpdateResetActionPerformed
        txtRequestUpdateSubject.setText("");
        txtRequestUpdateRequest.setText("");
        txtRequestUpdateSubject.grabFocus();
    }//GEN-LAST:event_btnRequestUpdateResetActionPerformed

    private void btnSearchStaffSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStaffSearchActionPerformed
        dataSource.searchStaffContact(txtSearchStaffFirstName.getText(), txtSearchStaffLastName.getText(), txtSearchStaffId.getText(), tblSearchStaff);
    }//GEN-LAST:event_btnSearchStaffSearchActionPerformed

    private void btnSearchStaffResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStaffResetActionPerformed
        txtSearchStaffId.setText("");
        txtSearchStaffFirstName.setText("");
        txtSearchStaffLastName.setText("");
    }//GEN-LAST:event_btnSearchStaffResetActionPerformed

    String studentID;

    public void viewProfile(String id) {
        studentID = id;
        Object profile[] = (Object[]) dataSource.viewProfileStudent(id);
        txtStudentViewProfileFirstName.setText(profile[0].toString());
        txtStudentViewProfileLastName.setText(profile[1].toString());
        txtStudentViewProfileID.setText(profile[2].toString());
        txtStudentViewProfilePassword.setText(profile[3].toString());
        txtStudentViewProfileAddress.setText(profile[4].toString());
        txtStudentViewProfileEmailID.setText(profile[5].toString());
        txtStudentViewProfilePhoneNo.setText(profile[6].toString());
        txtStudentViewProfileParentEmailID.setText(profile[7].toString());
        txtStudentViewProfileCourse.setText(profile[8].toString());
        txtStudentViewProfileParentPhoneNo.setText(profile[9].toString());
        txtStudentViewProfileRoomAlloted.setText(profile[10].toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Student().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequestUpdateReset;
    private javax.swing.JButton btnRequestUpdateSendRequest;
    private javax.swing.JButton btnSearchStaffReset;
    private javax.swing.JButton btnSearchStaffSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlRequestChange;
    private javax.swing.JPanel pnlSearchStaffContact;
    private javax.swing.JPanel pnlViewProfile;
    private javax.swing.JTabbedPane tbdStudent;
    private javax.swing.JTable tblSearchStaff;
    private javax.swing.JTextArea txtRequestUpdateRequest;
    private javax.swing.JTextField txtRequestUpdateSubject;
    private javax.swing.JTextField txtSearchStaffFirstName;
    private javax.swing.JTextField txtSearchStaffId;
    private javax.swing.JTextField txtSearchStaffLastName;
    private javax.swing.JTextField txtStudentViewProfileAddress;
    private javax.swing.JTextField txtStudentViewProfileCourse;
    private javax.swing.JTextField txtStudentViewProfileEmailID;
    private javax.swing.JTextField txtStudentViewProfileFirstName;
    private javax.swing.JTextField txtStudentViewProfileID;
    private javax.swing.JTextField txtStudentViewProfileLastName;
    private javax.swing.JTextField txtStudentViewProfileParentEmailID;
    private javax.swing.JTextField txtStudentViewProfileParentPhoneNo;
    private javax.swing.JTextField txtStudentViewProfilePassword;
    private javax.swing.JTextField txtStudentViewProfilePhoneNo;
    private javax.swing.JTextField txtStudentViewProfileRoomAlloted;
    // End of variables declaration//GEN-END:variables
}
